version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: puckel/docker-airflow:1.10.3
        restart: always
        depends_on:
            - postgres
        logging:
            driver: "json-file"
            options:
                max-file: "7"
                max-size: 1024m
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - APP_PROFILE=${APP_PROFILE}
            - APP_HOST=${APP_HOST}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./config/requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8383:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
